version: "3.7"

services:
  api:
    build: ../api
    environment:
      FLASK_APP: main
      FLASK_DEBUG: "true"
    ports:
      - 8082:8082
networks:
  default:
   external:
     name: intellisite
